/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VTApiPlaneraResaWebV4ModelsProductTypeEnum from './VTApiPlaneraResaWebV4ModelsProductTypeEnum';
import VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel from './VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel';

/**
 * The VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel model module.
 * @module model/VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel
 * @version v4
 */
class VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel {
    /**
     * Constructs a new <code>VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel</code>.
     * @alias module:model/VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel
     */
    constructor() { 
        
        VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel} obj Optional instance to populate.
     * @return {module:model/VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel} The populated <code>VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel();

            if (data.hasOwnProperty('ticketName')) {
                obj['ticketName'] = ApiClient.convertToType(data['ticketName'], 'String');
            }
            if (data.hasOwnProperty('configurations')) {
                obj['configurations'] = ApiClient.convertToType(data['configurations'], [VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel]);
            }
            if (data.hasOwnProperty('productType')) {
                obj['productType'] = VTApiPlaneraResaWebV4ModelsProductTypeEnum.constructFromObject(data['productType']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['ticketName'] && !(typeof data['ticketName'] === 'string' || data['ticketName'] instanceof String)) {
            throw new Error("Expected the field `ticketName` to be a primitive type in the JSON string but got " + data['ticketName']);
        }
        if (data['configurations']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['configurations'])) {
                throw new Error("Expected the field `configurations` to be an array in the JSON data but got " + data['configurations']);
            }
            // validate the optional field `configurations` (array)
            for (const item of data['configurations']) {
                VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} ticketName
 */
VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel.prototype['ticketName'] = undefined;

/**
 * @member {Array.<module:model/VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel>} configurations
 */
VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel.prototype['configurations'] = undefined;

/**
 * @member {module:model/VTApiPlaneraResaWebV4ModelsProductTypeEnum} productType
 */
VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel.prototype['productType'] = undefined;






export default VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel;

