/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class VTApiPlaneraResaWebV4ModelsSeverity.
* @enum {}
* @readonly
*/
export default class VTApiPlaneraResaWebV4ModelsSeverity {
    
        /**
         * value: "unknown"
         * @const
         */
        "unknown" = "unknown";

    
        /**
         * value: "low"
         * @const
         */
        "low" = "low";

    
        /**
         * value: "normal"
         * @const
         */
        "normal" = "normal";

    
        /**
         * value: "high"
         * @const
         */
        "high" = "high";

    

    /**
    * Returns a <code>VTApiPlaneraResaWebV4ModelsSeverity</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/VTApiPlaneraResaWebV4ModelsSeverity} The enum <code>VTApiPlaneraResaWebV4ModelsSeverity</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

