/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class VTApiPlaneraResaWebV4ModelsAgeType.
* @enum {}
* @readonly
*/
export default class VTApiPlaneraResaWebV4ModelsAgeType {
    
        /**
         * value: "adult"
         * @const
         */
        "adult" = "adult";

    
        /**
         * value: "youth"
         * @const
         */
        "youth" = "youth";

    
        /**
         * value: "senior"
         * @const
         */
        "senior" = "senior";

    
        /**
         * value: "schoolyouth"
         * @const
         */
        "schoolyouth" = "schoolyouth";

    
        /**
         * value: "other"
         * @const
         */
        "other" = "other";

    

    /**
    * Returns a <code>VTApiPlaneraResaWebV4ModelsAgeType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/VTApiPlaneraResaWebV4ModelsAgeType} The enum <code>VTApiPlaneraResaWebV4ModelsAgeType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

