/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel model module.
 * @module model/VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel
 * @version v4
 */
class VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel {
    /**
     * Constructs a new <code>VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel</code>.
     * Deep links to open Padam app with specific trip
     * @alias module:model/VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel
     */
    constructor() { 
        
        VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel} obj Optional instance to populate.
     * @return {module:model/VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel} The populated <code>VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel();

            if (data.hasOwnProperty('ios')) {
                obj['ios'] = ApiClient.convertToType(data['ios'], 'String');
            }
            if (data.hasOwnProperty('android')) {
                obj['android'] = ApiClient.convertToType(data['android'], 'String');
            }
            if (data.hasOwnProperty('web')) {
                obj['web'] = ApiClient.convertToType(data['web'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['ios'] && !(typeof data['ios'] === 'string' || data['ios'] instanceof String)) {
            throw new Error("Expected the field `ios` to be a primitive type in the JSON string but got " + data['ios']);
        }
        // ensure the json data is a string
        if (data['android'] && !(typeof data['android'] === 'string' || data['android'] instanceof String)) {
            throw new Error("Expected the field `android` to be a primitive type in the JSON string but got " + data['android']);
        }
        // ensure the json data is a string
        if (data['web'] && !(typeof data['web'] === 'string' || data['web'] instanceof String)) {
            throw new Error("Expected the field `web` to be a primitive type in the JSON string but got " + data['web']);
        }

        return true;
    }


}



/**
 * iOS link
 * @member {String} ios
 */
VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel.prototype['ios'] = undefined;

/**
 * Android link
 * @member {String} android
 */
VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel.prototype['android'] = undefined;

/**
 * Web link
 * @member {String} web
 */
VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel.prototype['web'] = undefined;






export default VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel;

