/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel model module.
 * @module model/VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel
 * @version v4
 */
class VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel {
    /**
     * Constructs a new <code>VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel</code>.
     * Shortened version of existing reconstruction reference
     * @alias module:model/VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel
     */
    constructor() { 
        
        VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel} obj Optional instance to populate.
     * @return {module:model/VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel} The populated <code>VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel();

            if (data.hasOwnProperty('shortenedReconstructionRef')) {
                obj['shortenedReconstructionRef'] = ApiClient.convertToType(data['shortenedReconstructionRef'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['shortenedReconstructionRef'] && !(typeof data['shortenedReconstructionRef'] === 'string' || data['shortenedReconstructionRef'] instanceof String)) {
            throw new Error("Expected the field `shortenedReconstructionRef` to be a primitive type in the JSON string but got " + data['shortenedReconstructionRef']);
        }

        return true;
    }


}



/**
 * @member {String} shortenedReconstructionRef
 */
VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel.prototype['shortenedReconstructionRef'] = undefined;






export default VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel;

