/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class VTApiPlaneraResaWebV4ModelsTransportSubMode.
* @enum {}
* @readonly
*/
export default class VTApiPlaneraResaWebV4ModelsTransportSubMode {
    
        /**
         * value: "unknown"
         * @const
         */
        "unknown" = "unknown";

    
        /**
         * value: "none"
         * @const
         */
        "none" = "none";

    
        /**
         * value: "vasttagen"
         * @const
         */
        "vasttagen" = "vasttagen";

    
        /**
         * value: "longdistancetrain"
         * @const
         */
        "longdistancetrain" = "longdistancetrain";

    
        /**
         * value: "regionaltrain"
         * @const
         */
        "regionaltrain" = "regionaltrain";

    

    /**
    * Returns a <code>VTApiPlaneraResaWebV4ModelsTransportSubMode</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/VTApiPlaneraResaWebV4ModelsTransportSubMode} The enum <code>VTApiPlaneraResaWebV4ModelsTransportSubMode</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

