/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VTApiPlaneraResaWebV4ModelsAgeType from './VTApiPlaneraResaWebV4ModelsAgeType';

/**
 * The VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel model module.
 * @module model/VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel
 * @version v4
 */
class VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel {
    /**
     * Constructs a new <code>VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel</code>.
     * @alias module:model/VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel
     */
    constructor() { 
        
        VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel} obj Optional instance to populate.
     * @return {module:model/VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel} The populated <code>VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel();

            if (data.hasOwnProperty('productId')) {
                obj['productId'] = ApiClient.convertToType(data['productId'], 'Number');
            }
            if (data.hasOwnProperty('validityLength')) {
                obj['validityLength'] = ApiClient.convertToType(data['validityLength'], 'Number');
            }
            if (data.hasOwnProperty('itemPrice')) {
                obj['itemPrice'] = ApiClient.convertToType(data['itemPrice'], 'Number');
            }
            if (data.hasOwnProperty('offerSpecification')) {
                obj['offerSpecification'] = ApiClient.convertToType(data['offerSpecification'], 'String');
            }
            if (data.hasOwnProperty('ageType')) {
                obj['ageType'] = VTApiPlaneraResaWebV4ModelsAgeType.constructFromObject(data['ageType']);
            }
            if (data.hasOwnProperty('zoneIds')) {
                obj['zoneIds'] = ApiClient.convertToType(data['zoneIds'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['offerSpecification'] && !(typeof data['offerSpecification'] === 'string' || data['offerSpecification'] instanceof String)) {
            throw new Error("Expected the field `offerSpecification` to be a primitive type in the JSON string but got " + data['offerSpecification']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['zoneIds'])) {
            throw new Error("Expected the field `zoneIds` to be an array in the JSON data but got " + data['zoneIds']);
        }

        return true;
    }


}



/**
 * @member {Number} productId
 */
VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel.prototype['productId'] = undefined;

/**
 * @member {Number} validityLength
 */
VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel.prototype['validityLength'] = undefined;

/**
 * @member {Number} itemPrice
 */
VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel.prototype['itemPrice'] = undefined;

/**
 * @member {String} offerSpecification
 */
VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel.prototype['offerSpecification'] = undefined;

/**
 * @member {module:model/VTApiPlaneraResaWebV4ModelsAgeType} ageType
 */
VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel.prototype['ageType'] = undefined;

/**
 * @member {Array.<String>} zoneIds
 */
VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel.prototype['zoneIds'] = undefined;






export default VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel;

