/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class VTApiPlaneraResaWebV4ModelsTravellerCategory.
* @enum {}
* @readonly
*/
export default class VTApiPlaneraResaWebV4ModelsTravellerCategory {
    
        /**
         * value: "unknown"
         * @const
         */
        "unknown" = "unknown";

    
        /**
         * value: "adult"
         * @const
         */
        "adult" = "adult";

    
        /**
         * value: "youth"
         * @const
         */
        "youth" = "youth";

    

    /**
    * Returns a <code>VTApiPlaneraResaWebV4ModelsTravellerCategory</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/VTApiPlaneraResaWebV4ModelsTravellerCategory} The enum <code>VTApiPlaneraResaWebV4ModelsTravellerCategory</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

