/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel model module.
 * @module model/VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel
 * @version v4
 */
class VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel {
    /**
     * Constructs a new <code>VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel</code>.
     * Contains detailed information about a direction and its components.
     * @alias module:model/VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel
     */
    constructor() { 
        
        VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel} obj Optional instance to populate.
     * @return {module:model/VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel} The populated <code>VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel();

            if (data.hasOwnProperty('fullDirection')) {
                obj['fullDirection'] = ApiClient.convertToType(data['fullDirection'], 'String');
            }
            if (data.hasOwnProperty('shortDirection')) {
                obj['shortDirection'] = ApiClient.convertToType(data['shortDirection'], 'String');
            }
            if (data.hasOwnProperty('replaces')) {
                obj['replaces'] = ApiClient.convertToType(data['replaces'], 'String');
            }
            if (data.hasOwnProperty('via')) {
                obj['via'] = ApiClient.convertToType(data['via'], 'String');
            }
            if (data.hasOwnProperty('isFreeService')) {
                obj['isFreeService'] = ApiClient.convertToType(data['isFreeService'], 'Boolean');
            }
            if (data.hasOwnProperty('isPaidService')) {
                obj['isPaidService'] = ApiClient.convertToType(data['isPaidService'], 'Boolean');
            }
            if (data.hasOwnProperty('isSwimmingService')) {
                obj['isSwimmingService'] = ApiClient.convertToType(data['isSwimmingService'], 'Boolean');
            }
            if (data.hasOwnProperty('isDirectDestinationBus')) {
                obj['isDirectDestinationBus'] = ApiClient.convertToType(data['isDirectDestinationBus'], 'Boolean');
            }
            if (data.hasOwnProperty('isFrontEntry')) {
                obj['isFrontEntry'] = ApiClient.convertToType(data['isFrontEntry'], 'Boolean');
            }
            if (data.hasOwnProperty('isExtraBus')) {
                obj['isExtraBus'] = ApiClient.convertToType(data['isExtraBus'], 'Boolean');
            }
            if (data.hasOwnProperty('isExtraBoat')) {
                obj['isExtraBoat'] = ApiClient.convertToType(data['isExtraBoat'], 'Boolean');
            }
            if (data.hasOwnProperty('isExtraTram')) {
                obj['isExtraTram'] = ApiClient.convertToType(data['isExtraTram'], 'Boolean');
            }
            if (data.hasOwnProperty('isSchoolBus')) {
                obj['isSchoolBus'] = ApiClient.convertToType(data['isSchoolBus'], 'Boolean');
            }
            if (data.hasOwnProperty('isExpressBus')) {
                obj['isExpressBus'] = ApiClient.convertToType(data['isExpressBus'], 'Boolean');
            }
            if (data.hasOwnProperty('fortifiesLine')) {
                obj['fortifiesLine'] = ApiClient.convertToType(data['fortifiesLine'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['fullDirection'] && !(typeof data['fullDirection'] === 'string' || data['fullDirection'] instanceof String)) {
            throw new Error("Expected the field `fullDirection` to be a primitive type in the JSON string but got " + data['fullDirection']);
        }
        // ensure the json data is a string
        if (data['shortDirection'] && !(typeof data['shortDirection'] === 'string' || data['shortDirection'] instanceof String)) {
            throw new Error("Expected the field `shortDirection` to be a primitive type in the JSON string but got " + data['shortDirection']);
        }
        // ensure the json data is a string
        if (data['replaces'] && !(typeof data['replaces'] === 'string' || data['replaces'] instanceof String)) {
            throw new Error("Expected the field `replaces` to be a primitive type in the JSON string but got " + data['replaces']);
        }
        // ensure the json data is a string
        if (data['via'] && !(typeof data['via'] === 'string' || data['via'] instanceof String)) {
            throw new Error("Expected the field `via` to be a primitive type in the JSON string but got " + data['via']);
        }
        // ensure the json data is a string
        if (data['fortifiesLine'] && !(typeof data['fortifiesLine'] === 'string' || data['fortifiesLine'] instanceof String)) {
            throw new Error("Expected the field `fortifiesLine` to be a primitive type in the JSON string but got " + data['fortifiesLine']);
        }

        return true;
    }


}



/**
 * The original direction string.
 * @member {String} fullDirection
 */
VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel.prototype['fullDirection'] = undefined;

/**
 * The direction string after parsing and removing the different components.
 * @member {String} shortDirection
 */
VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel.prototype['shortDirection'] = undefined;

/**
 * The name of the replaced line, if any. Parses and replaces the following component: \", Ersätter [replaces]\"
 * @member {String} replaces
 */
VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel.prototype['replaces'] = undefined;

/**
 * The name of the via location, if any. Parses and replaces the following component: \", via [via]\"
 * @member {String} via
 */
VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel.prototype['via'] = undefined;

/**
 * Whether the service is free. Parses and replaces the following component: \", Fri resa\"
 * @member {Boolean} isFreeService
 */
VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel.prototype['isFreeService'] = undefined;

/**
 * Whether the service is paid. Parses and replaces the following component: \", Avgiftsbelagd tur\"
 * @member {Boolean} isPaidService
 */
VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel.prototype['isPaidService'] = undefined;

/**
 * Whether the service is a swimming service. Parses and replaces the following component: \", Badbuss\"
 * @member {Boolean} isSwimmingService
 */
VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel.prototype['isSwimmingService'] = undefined;

/**
 * Whether the service is a direct destination bus. Parses and replaces the following component: \", Direktbuss\"
 * @member {Boolean} isDirectDestinationBus
 */
VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel.prototype['isDirectDestinationBus'] = undefined;

/**
 * Whether the service has front entry. Parses and replaces the following component: \", Påstigning fram\"
 * @member {Boolean} isFrontEntry
 */
VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel.prototype['isFrontEntry'] = undefined;

/**
 * Whether the service is an extra bus. Parses and replaces the following component: \", Extrabuss\"
 * @member {Boolean} isExtraBus
 */
VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel.prototype['isExtraBus'] = undefined;

/**
 * Whether the service is an extra boat. Parses and replaces the following component: \", Extrabåt\"
 * @member {Boolean} isExtraBoat
 */
VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel.prototype['isExtraBoat'] = undefined;

/**
 * Whether the service is an extra tram. Parses and replaces the following component: \", Extravagn\"
 * @member {Boolean} isExtraTram
 */
VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel.prototype['isExtraTram'] = undefined;

/**
 * Whether the service is a school bus. Parses and replaces the following component: \", Skolbuss\"
 * @member {Boolean} isSchoolBus
 */
VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel.prototype['isSchoolBus'] = undefined;

/**
 * Whether the service is an express bus. Parses and replaces the following component: \", Snabbuss\"
 * @member {Boolean} isExpressBus
 */
VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel.prototype['isExpressBus'] = undefined;

/**
 * The name of the fortified line, if any. Parses and replaces the following component: \", Fortifies [fortifies]\"
 * @member {String} fortifiesLine
 */
VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel.prototype['fortifiesLine'] = undefined;






export default VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel;

