/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class VTApiPlaneraResaWebV4ModelsAreaType.
* @enum {}
* @readonly
*/
export default class VTApiPlaneraResaWebV4ModelsAreaType {
    
        /**
         * value: "none"
         * @const
         */
        "none" = "none";

    
        /**
         * value: "standard"
         * @const
         */
        "standard" = "standard";

    
        /**
         * value: "mini"
         * @const
         */
        "mini" = "mini";

    
        /**
         * value: "extra"
         * @const
         */
        "extra" = "extra";

    
        /**
         * value: "leisure"
         * @const
         */
        "leisure" = "leisure";

    

    /**
    * Returns a <code>VTApiPlaneraResaWebV4ModelsAreaType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/VTApiPlaneraResaWebV4ModelsAreaType} The enum <code>VTApiPlaneraResaWebV4ModelsAreaType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

