/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class VTApiPlaneraResaWebV4ModelsProductTypeEnum.
* @enum {}
* @readonly
*/
export default class VTApiPlaneraResaWebV4ModelsProductTypeEnum {
    
        /**
         * value: "single"
         * @const
         */
        "single" = "single";

    
        /**
         * value: "period"
         * @const
         */
        "period" = "period";

    
        /**
         * value: "shortterm"
         * @const
         */
        "shortterm" = "shortterm";

    
        /**
         * value: "school"
         * @const
         */
        "school" = "school";

    
        /**
         * value: "event"
         * @const
         */
        "event" = "event";

    
        /**
         * value: "flex"
         * @const
         */
        "flex" = "flex";

    
        /**
         * value: "seasonal"
         * @const
         */
        "seasonal" = "seasonal";

    

    /**
    * Returns a <code>VTApiPlaneraResaWebV4ModelsProductTypeEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/VTApiPlaneraResaWebV4ModelsProductTypeEnum} The enum <code>VTApiPlaneraResaWebV4ModelsProductTypeEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

