/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class VTApiPlaneraResaWebV4ModelsLocationType.
* @enum {}
* @readonly
*/
export default class VTApiPlaneraResaWebV4ModelsLocationType {
    
        /**
         * value: "unknown"
         * @const
         */
        "unknown" = "unknown";

    
        /**
         * value: "stoparea"
         * @const
         */
        "stoparea" = "stoparea";

    
        /**
         * value: "stoppoint"
         * @const
         */
        "stoppoint" = "stoppoint";

    
        /**
         * value: "address"
         * @const
         */
        "address" = "address";

    
        /**
         * value: "pointofinterest"
         * @const
         */
        "pointofinterest" = "pointofinterest";

    
        /**
         * value: "metastation"
         * @const
         */
        "metastation" = "metastation";

    

    /**
    * Returns a <code>VTApiPlaneraResaWebV4ModelsLocationType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/VTApiPlaneraResaWebV4ModelsLocationType} The enum <code>VTApiPlaneraResaWebV4ModelsLocationType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

