/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import VTApiPlaneraResaWebV4ModelsApiError from '../model/VTApiPlaneraResaWebV4ModelsApiError';
import VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel from '../model/VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel';

/**
* Products service.
* @module api/ProductsApi
* @version v4
*/
export default class ProductsApi {

    /**
    * Constructs a new ProductsApi. 
    * @alias module:api/ProductsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the productsJourneyticketGet operation.
     * @callback module:api/ProductsApi~productsJourneyticketGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns least expensive ticket products between origin and destination for adult and youth.
     * A position reference for origin can be originGid or a LatLong specified by both originLatitude and originLongitude                A position reference for destination can be destinationGid or a LatLong specified by both destinationLatitude and destinationLongitude                For an origin or destination to be valid, either a gid or a combination of latitude and longitude must be specified. A Gid takes precedence over latitude/longitude.                Sample request:                    GET /products/journeyticket?originGid=9021014001760000&destinationGid=9021014003980000                or                    GET /products/journeyticket?originLongitude=12.63308&originLatitude=58.028237&destinationLongitude=11.930897&destinationLatitude=57.586085
     * @param {Object} opts Optional parameters
     * @param {String} [originGid] The 16-digit Västtrafik gid of the origin location (which could be either a stop area (e.g. '9021014001760000'), a stop point (e.g. '9022014001760004') or meta-station (e.g. '0000000800000022')).
     * @param {Number} [originLatitude] The latitude of the origin location.
     * @param {Number} [originLongitude] The longitude of the origin location.
     * @param {String} [destinationGid] The 16-digit Västtrafik gid of the destination location (which could be either a stop area, stop point or meta-station).
     * @param {Number} [destinationLatitude] The latitude of the destination location.
     * @param {Number} [destinationLongitude] The longitude of the destination location.
     * @param {module:api/ProductsApi~productsJourneyticketGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel>}
     */
    productsJourneyticketGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'originGid': opts['originGid'],
        'originLatitude': opts['originLatitude'],
        'originLongitude': opts['originLongitude'],
        'destinationGid': opts['destinationGid'],
        'destinationLatitude': opts['destinationLatitude'],
        'destinationLongitude': opts['destinationLongitude']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['auth'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel];
      return this.apiClient.callApi(
        '/products/journeyticket', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
