/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PlaneraResa);
  }
}(this, function(expect, PlaneraResa) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel', function() {
    it('should create an instance of VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel', function() {
      // uncomment below and update the code to test VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel
      //var instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel();
      //expect(instance).to.be.a(PlaneraResa.VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel);
    });

    it('should have the property fullDirection (base name: "fullDirection")', function() {
      // uncomment below and update the code to test the property fullDirection
      //var instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel();
      //expect(instance).to.be();
    });

    it('should have the property shortDirection (base name: "shortDirection")', function() {
      // uncomment below and update the code to test the property shortDirection
      //var instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel();
      //expect(instance).to.be();
    });

    it('should have the property replaces (base name: "replaces")', function() {
      // uncomment below and update the code to test the property replaces
      //var instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel();
      //expect(instance).to.be();
    });

    it('should have the property via (base name: "via")', function() {
      // uncomment below and update the code to test the property via
      //var instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel();
      //expect(instance).to.be();
    });

    it('should have the property isFreeService (base name: "isFreeService")', function() {
      // uncomment below and update the code to test the property isFreeService
      //var instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel();
      //expect(instance).to.be();
    });

    it('should have the property isPaidService (base name: "isPaidService")', function() {
      // uncomment below and update the code to test the property isPaidService
      //var instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel();
      //expect(instance).to.be();
    });

    it('should have the property isSwimmingService (base name: "isSwimmingService")', function() {
      // uncomment below and update the code to test the property isSwimmingService
      //var instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel();
      //expect(instance).to.be();
    });

    it('should have the property isDirectDestinationBus (base name: "isDirectDestinationBus")', function() {
      // uncomment below and update the code to test the property isDirectDestinationBus
      //var instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel();
      //expect(instance).to.be();
    });

    it('should have the property isFrontEntry (base name: "isFrontEntry")', function() {
      // uncomment below and update the code to test the property isFrontEntry
      //var instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel();
      //expect(instance).to.be();
    });

    it('should have the property isExtraBus (base name: "isExtraBus")', function() {
      // uncomment below and update the code to test the property isExtraBus
      //var instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel();
      //expect(instance).to.be();
    });

    it('should have the property isExtraBoat (base name: "isExtraBoat")', function() {
      // uncomment below and update the code to test the property isExtraBoat
      //var instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel();
      //expect(instance).to.be();
    });

    it('should have the property isExtraTram (base name: "isExtraTram")', function() {
      // uncomment below and update the code to test the property isExtraTram
      //var instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel();
      //expect(instance).to.be();
    });

    it('should have the property isSchoolBus (base name: "isSchoolBus")', function() {
      // uncomment below and update the code to test the property isSchoolBus
      //var instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel();
      //expect(instance).to.be();
    });

    it('should have the property isExpressBus (base name: "isExpressBus")', function() {
      // uncomment below and update the code to test the property isExpressBus
      //var instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel();
      //expect(instance).to.be();
    });

    it('should have the property fortifiesLine (base name: "fortifiesLine")', function() {
      // uncomment below and update the code to test the property fortifiesLine
      //var instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel();
      //expect(instance).to.be();
    });

  });

}));
